version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: work3_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - work3_db:/var/lib/mysql
      - ./www/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: work5_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: work3_apache
    restart: unless-stopped
    depends_on:
      - db
      - redis
    expose:
      - "80"
    volumes:
      - ./www:/var/www/app:rw

  nginx:
    image: nginx:stable
    container_name: work3_nginx
    restart: unless-stopped
    depends_on:
      - apache
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www/static:/var/www/static:ro
      - ./www:/var/www/app:ro

volumes:
  work3_db:
